packaging_format = 2

id = "moncycle"
name = "Moncycle"
description.en = "Menstrual cycle follow-up for natural family planning"
description.fr = "Suivi de cycle pour les méthodes naturelles de régulation de naissance"

version = "14~ynh3"

maintainers = ["Raoul de Limezy"]

[upstream]
license = "CC-BY-NC-SA-4.0"
website = "https://moncycle.app"
demo = "https://tableau.moncycle.app/connexion.php?email1=demo.bill@moncycle.app&mdp=demo"
code = "https://github.com/jean-io/moncycle.app"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "100M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"

[resources]
        [resources.sources.main]
        url = "https://github.com/jean-io/moncycle.app/archive/ac1eca57db85f049063ca77911c842b0aeb6258a.zip"
        sha256 = "ac08ed823aa6b11b3c666a5abb02e97faa473522c965eb6b02565b9a8eadce96"
        autoupdate.strategy = "latest_github_release"

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "mariadb-server, php8.3-gd, php8.3-mysql, php8.3-xml, php8.3-mbstring, php8.3-opcache"

    [resources.database]
    type = "mysql"
